# Generated by Django 3.0.2 on 2020-04-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
