# Generated by Django 3.0.2 on 2020-04-06 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_date',
            name='date_id',
        ),
    ]
