# Generated by Django 3.0.2 on 2020-04-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0002_auto_20200411_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='date',
            field=models.DateField(),
        ),
    ]
