# Generated by Django 3.0.2 on 2020-04-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0002_remove_task_date_date_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_add',
            name='status',
            field=models.CharField(default='active', max_length=100),
        ),
    ]
