# Generated by Django 3.0.2 on 2020-04-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0003_task_add_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_add',
            old_name='task',
            new_name='title',
        ),
        migrations.AddField(
            model_name='task_add',
            name='content',
            field=models.CharField(blank=True, default='', max_length=100000, null=True),
        ),
    ]
