# Generated by Django 3.0.2 on 2020-04-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0005_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
